### ISSUE TITLE
Create python-package-conda.yml #6125

### ISSUE THREAD

**Issue by Neiland85** [pypa/pipenv#6160]
Create python-package-conda.yml #6125

_Originally posted by @Neiland85 in https://github.com/pypa/pipenv/pull/6159#pullrequestreview-2070626260_
            
```[tasklist]
### Tasks
- [ ] https://github.com/pypa/pipenv/pull/6159
- [ ] https://github.com/pypa/pipenv/issues/6125
- [ ] https://github.com/pypa/pipenv/issues/5604
- [ ] https://github.com/pypa/pipenv/issues/6109
```

```[tasklist]
### Tasks
- [ ] https://github.com/pypa/pipenv/issues/6109
```

**Comment by oz123** [comment]
Spam...?

**Comment by Neiland85** [comment]
noup

**Comment by Neiland85** [comment]
science, yah!
